### ISSUE TITLE
Access data ?

### ISSUE THREAD

**Issue by tescrihuela** [VictimOfMaths/Maps#1]
Hello,

I noticed one of your map on Twitter and I find it so cool, great work ! And thanks for sharing the code on Github.
I tried to generate one of your bivariate map (sun vs rain), and so, I wondered if there was any way to "add" the input data somewhere ? Maybe it is too large for a github repo ?

Thanks !

**Comment by VictimOfMaths** [comment]
Hi, unfortunately the two files are too large to upload to GitHub. They can be downloaded freely from the sources provided though.

Colin
